name: Deploy to Staging

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    uses: ./.github/workflows/shared_deployment_logic.yml
    with:
      image_tag: staging-${{ github.sha }}
      environment: staging 
    secrets:
      inherit: true