name: Test scp

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow on Git tags starting with "v"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Set Docker Image Tag
      - name: Set Docker Image Tag
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            if [ "${{ github.ref_type }}" == "tag" ]; then
              echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
            else
              echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            fi
          else
            echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          fi
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}


      - name: Transfer docker-compose.yml to Production
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ./docker-compose.yml
          target: /home/${{ secrets.PRODUCTION_USER }}/docker-compose.yml
          debug: true

